name = "OMOPCDMFeasibility"
uuid = "d7c4b303-36e6-42c5-a114-1784c141c4f7"
authors = ["Kosuri Lakshmi Indu <kosurilindu@gmail.com> and contributors"]
version = "0.0.1"

[deps]
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
FunSQL = "cf6cc811-59f4-4a10-b258-a8547a8f6407"
InlineStrings = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
OMOPCommonDataModel = "ba65db9e-6590-4054-ab8a-101ed9124986"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
DBInterface = "2.6.1"
DataFrames = "1.7.0"
DuckDB = "1.3.2"
FunSQL = "0.15"
InlineStrings = "1.4.4"
OMOPCommonDataModel = "0.1"
PrettyTables = "2.4.0"
Serialization = "1.11.0"
Tables = "1.12.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
