[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
OMOPCDMFeasibility = "d7c4b303-36e6-42c5-a114-1784c141c4f7"

[compat]
Documenter = "1"
DocumenterVitepress = "0.2"
julia = "1.10"
