[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
OMOPCDMFeasibility = "d7c4b303-36e6-42c5-a114-1784c141c4f7"

[compat]
Documenter = "1"
DocumenterTools = "0.1.20"
LiveServer = "1.5"
julia = "1.10"
